# -*- coding: utf-8 -*-
"""Agglomerative.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHv_eqiYTUaa1xQUgTNDljzFuNlJ39HQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#read the dataset file
df=pd.read_csv("customer.csv")

#no of rows and columns
df.shape

#to check whether any value is null and data is clean
df.isnull().sum()

#Ploting as per annual income wise spending score
#taking all rows and 3rd and 4th column
#and taking it into arrays using "values"
X=df.iloc[:,[3,4]].values
X

#Scatter plot of column 1 with column 0
plt.scatter(X[...,0],X[...,1])
plt.xlabel('Total Income')
plt.ylabel('Spending Score')
plt.show()

#To check no. of clusters
#ward= Euclidean distance
import scipy.cluster.hierarchy as sch
dendrogram=sch.dendrogram(sch.linkage(X,method='ward'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean Distances')
plt.show()

#Considering 5 clusters
from sklearn.cluster import AgglomerativeClustering
hc= AgglomerativeClustering(n_clusters=5,affinity='euclidean',linkage='ward')
Y_hc=hc.fit_predict(X)
Y_hc

plt.scatter(X[Y_hc==0,0],X[Y_hc==0,1],label='Cluster 1')
plt.scatter(X[Y_hc==1,0],X[Y_hc==1,1],label='Cluster 2')
plt.scatter(X[Y_hc==2,0],X[Y_hc==2,1],label='Cluster 3')
plt.scatter(X[Y_hc==3,0],X[Y_hc==3,1],label='Cluster 4')
plt.scatter(X[Y_hc==4,0],X[Y_hc==4,1],label='Cluster 5')
plt.legend()
plt.show()

df['Target']=Y_hc
df

plt.scatter(X[...,0],X[...,1])
plt.show()