# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tXhA5S5dtpBpvviWstviijwy9SgXlupI

##### Customer Segmentation based on purchase history, interests, or activity monitoring Dataset provided as attached file.
"""

# [$] Load the Required Modules =>

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# [$] Load the Dataset =>

df = pd.read_csv('customers.csv')

# [$] Display the Dataset => Display First 5 Rows =>

df.head()

# [$] Get Dataset Informaion =>

df.info()

# [$] Take Only Required Dataset =>

final_df = df.drop(["CustomerID","Gender","Age"],axis=1)

# [$] Display Final DF =>

final_df.head()

plt.figure(figsize=(5,5),facecolor='white')
plt.scatter(df['Annual Income (k$)'], df['Spending Score (1-100)'])

# [$] With Elbow Method Find Optimal No Of Clusters =>

from sklearn.cluster import KMeans

wcss = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i)
    kmeans.fit_predict(final_df)
    wcss.append(kmeans.inertia_)

# [$] Plot WCSS =>
plt.figure(figsize=(5,5),facecolor='white')
plt.plot(range(1,11),wcss)

# [$] Elbow Is On 5 => K => Optimal Cluster =>

# [$] Convert dataframe to Numpy Arrays =>
X = final_df.iloc[:,:].values

# [$] Do Clustering With K = 5=>

kmeans = KMeans(n_clusters=5)
y_means = kmeans.fit_predict(X)

# [$] Draw Graph Of Clustering =>

plt.figure(figsize=(5,5),facecolor='white')

plt.scatter(X[y_means==0,0],X[y_means==0,1],color='red')
plt.scatter(X[y_means==1,0],X[y_means==1,1],color='blue')
plt.scatter(X[y_means==2,0],X[y_means==2,1],color='black')
plt.scatter(X[y_means==3,0],X[y_means==3,1],color='pink')
plt.scatter(X[y_means==4,0],X[y_means==4,1],color='orange')

# [$] So as you can see that We have Created Clustesrs Of Customer => Customer Segemnetation => On Basis Of Annual Income & Spending Score =>

# Total_Clusters = 5